[from-internal]
exten => _XXX,1,NoOp(Ramal ${EXTEN} - Tenant test.local)
 same => n,Dial(PJSIP/${EXTEN})

exten => *65,1,Ringing()
 same => n,Wait(7)
 same => n,Answer()
 same => n,MusicOnHold(default) 
 same => n,Hangup()

exten => 60,1,Answer()
 same => n,Queue(suporte) 
 same => n,Hangup()

exten => 61,1,Answer()
 same => n,Queue(financeiro) 
 same => n,Hangup()

; Hints (BLF)
exten => 101,hint,PJSIP/101&Custom:REG-test.local-101
exten => 102,hint,PJSIP/102&Custom:REG-test.local-102

exten => h,1,Hangup()
