[modules]
autoload=yes

noload = chan_sip.so
noload = res_config_mysql.so
noload = chan_mobile.so
noload = app_mysql.so
noload = cdr_mysql.so
noload = cdr_custom.so
noload = pbx_ael.so
noload = app_festival.so
noload = app_followme.so
noload = app_minivm.so
noload = app_osplookup.so
;noload = cdr_manager.so
noload = cdr_odbc.so
noload = cdr_pgsql.so
noload = cdr_radius.so
noload = cdr_sqlite3_custom.so
noload = cdr_tds.so
noload = cel_custom.so
noload = cel_odbc.so
noload = cel_pgsql.so
noload = cel_radius.so
noload = cel_sqlite3_custom.so
noload = chan_alsa.so
noload = chan_mgcp.so
noload = chan_ooh323.so
noload = chan_oss.so
noload = chan_motif.so
noload = res_fax_spandsp.so
noload = res_calendar_exchange.so
noload = res_calendar_ews.so
noload = res_calendar_caldav.so
noload = res_calendar_icalendar.so
noload = pbx_lua.so
noload = res_calendar.so
noload = res_config_ldap.so
noload = res_config_pgsql.so
noload = res_config_sqlite3.so
noload = res_fax.so
noload = res_snmp.so
noload = res_statsd.so
noload = res_stun_monitor.so
noload = res_xmpp.so
noload = cdr_adaptive_odbc.so
noload = chan_unistim.so
noload = res_corosync.so
noload = res_pjsip_stir_shaken.so
noload => res_resolver_unbound.so
noload => res_stir_shaken.so
noload => res_pjsip_endpoint_identifier_anonymous.so

