[transport-udp]
type=transport
protocol=udp
protocol=udp
bind=0.0.0.0:5060
;local_net=10.4.0.18
external_media_address=192.168.1.113
external_signaling_address=192.168.1.113

[kamailio-aor]
type = aor
contact = sip:kamailio.kamailio-asterisk-redis-test_voip-net:5060
qualify_frequency = 0

[101.test.local]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw,alaw
aors=kamailio-aor


[102.test.local]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw,alaw
aors=kamailio-aor

