[general]
realtime_family = queues
language = pt-br
persistentmembers = yes
autofill = yes
monitor-type = MixMonitor
ringinuse = no
setinterfacevar = yes
setqueueentryvar = yes
setqueuevar = yes
updatecdr = yes
negative_penalty_invalid = yes

[queue_template](!)
timeout=15
retry=1
ringinuse=no
announce-frequency= 0
announce-holdtime = no
reportholdtime = no
servicelevel = 120


[suporte](queue_template)
strategy = ringall
timeout = 30
musiconhold = default
member => Local/101@from-internal/n,1,101,hint:101@from-internal,no
member => Local/102@from-internal/n,2,102,hint:102@from-internal,no


[financeiro](queue_template)
strategy = ringall
timeout = 30
musiconhold = default