[from-internal]
exten => _XXX,1,NoOp(Ramal ${EXTEN} - Tenant test.local)
 same => n,Dial(PJSIP/${EXTEN})

; Hints (BLF)
exten => 101,hint,PJSIP/101&Custom:REG-test.local-101
exten => 102,hint,PJSIP/102&Custom:REG-test.local-102

exten => h,1,Hangup()